#using data base grocery;
use grocery;
# Solving the Quries

-- 1️. Customer Insights
-- Gain an understanding of customer engagement and purchasing behavior.

# 1 How many unique customers have placed orders?

select count(distinct cust_id) from orders;

# 2 Which customers have placed the highest number of orders?
select c.cust_id, c.cust_name, COUNT(o.ord_id) as total_orders
from customers c
join orders o on c.cust_id = o.cust_id
group by c.cust_id, c.cust_name
order by total_orders desc;


# 3 What is the total and average purchase value per customer?
select c.cust_id,c.cust_name,
sum(od.total_price) as Total_Purchase,
avg(od.total_price) as Avrage_Price
from customers c
join orders o on c.cust_id=o.cust_id
join order_details od on o.ord_id = od.ord_id
group by c.cust_id,c.cust_name
order by total_Purchase desc;

# 4 Who are the top 5 customers by total purchase amount?
select c.cust_id,c.cust_name,
sum(od.total_price) as Total_Purchase
from customers c
join orders o on c.cust_id=o.cust_id
join order_details od on o.ord_id = od.ord_id
group by c.cust_id,c.cust_name
order by total_Purchase desc limit 5;


-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.

# 1 How many products exist in each category?
select c.cat_id,c.cat_name, count(p.prod_id) as total_products
from categories c 
left join products p on p.cat_id=c.cat_id
group by c.cat_id,c.cat_name;


# 2 What is the average price of products by category?
select c.cat_id,c.cat_name, avg(p.price) as Average_price
from categories c 
left join products p on p.cat_id=c.cat_id
group by c.cat_id,c.cat_name;

# 3 Which products have the highest total sales volume (by quantity)?
select p.prod_id,p.prod_name,sum(od.quantity) as sales_volume
from products p
join order_details od on p.prod_id=od.prod_id
group by p.prod_id, p.prod_name
order by sales_volume desc;

# 4 What is the total revenue generated by each product?
select p.prod_id,p.prod_name,sum(od.quantity * p.price) as total_revenue_by_products
from products p
join order_details od on p.prod_id=od.prod_id
group by p.prod_id,p.prod_name
order by total_revenue_by_products desc;

# 5 How do product sales vary by category and supplier?
select c.cat_name, s.sup_name, 
       SUM(od.quantity) AS total_quantity_sold,
       SUM(od.total_price) AS total_revenue
from order_details od
join products p on od.prod_id = p.prod_id
join categories c on p.cat_id = c.cat_id
join supplier s on p.sup_id = s.sup_id
group by c.cat_name, s.sup_name
order by total_revenue desc;


-- 3. Sales and Order Trends
-- Analyze business performance through orders and revenue over time.

-- How many orders have been placed in total?
select count(ord_id) as total_order
from orders;

-- What is the average value per order?
SELECT AVG(order_total) AS avg_order_value
FROM (
    SELECT o.ord_id, SUM(od.total_price) AS order_total
    FROM orders o
    JOIN order_details od ON o.ord_id = od.ord_id
    GROUP BY o.ord_id
) AS order_summary;

-- On which dates were the most orders placed?
select order_date, COUNT(ord_id) as total_orders
from orders
group by order_date
order by total_orders desc;

-- What are the monthly trends in order volume and revenue?
SELECT DATE_FORMAT(STR_TO_DATE(order_date, '%m/%d/%Y'), '%m-%Y') AS month,
       COUNT(DISTINCT o.ord_id) AS order_count,
       SUM(od.total_price) AS total_revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY month
ORDER BY month;


-- How do order patterns vary across weekdays and weekends?
SELECT 
    CASE 
        WHEN DAYOFWEEK(STR_TO_DATE(order_date, '%Y-%m-%d')) IN (1,7) THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    COUNT(DISTINCT o.ord_id) AS order_count,
    SUM(od.total_price) AS total_revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY day_type;


-- 4️. Supplier Contribution
-- Identify the most active and profitable suppliers.

-- How many suppliers are there in the database?
SELECT COUNT(*) AS total_suppliers
FROM supplier;

-- Which supplier provides the most products?
SELECT s.sup_id, s.sup_name, COUNT(p.prod_id) AS total_products
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY total_products DESC;

-- What is the average price of products from each supplier?
SELECT s.sup_id, s.sup_name, AVG(p.price) AS avg_price
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY avg_price DESC;

-- Which suppliers contribute the most to total product sales (by revenue)?
SELECT s.sup_id, s.sup_name, SUM(od.total_price) AS total_revenue
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY s.sup_id, s.sup_name
ORDER BY total_revenue DESC;

-- 5️. Employee Performance
-- Assess how employees are handling and influencing sales.
-- How many employees have processed orders?
SELECT COUNT(DISTINCT emp_id) AS employees_with_orders
FROM orders;

-- Which employees have handled the most orders?
SELECT e.emp_id, e.emp_name, COUNT(o.ord_id) AS total_orders
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
GROUP BY e.emp_id, e.emp_name
ORDER BY total_orders DESC;

-- What is the total sales value processed by each employee?
SELECT e.emp_id, e.emp_name, SUM(od.total_price) AS total_sales
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY e.emp_id, e.emp_name
ORDER BY total_sales DESC;


-- What is the average order value handled per employee?
SELECT e.emp_id, e.emp_name, 
       AVG(order_total) AS avg_order_value
FROM employees e
JOIN (
    SELECT o.emp_id, o.ord_id, SUM(od.total_price) AS order_total
    FROM orders o
    JOIN order_details od ON o.ord_id = od.ord_id
    GROUP BY o.emp_id, o.ord_id
) emp_orders ON e.emp_id = emp_orders.emp_id
GROUP BY e.emp_id, e.emp_name
ORDER BY avg_order_value DESC;


-- 6️. Order Details Deep Dive
-- Explore item-level sales patterns and pricing behavior.
-- What is the relationship between quantity ordered and total price?
SELECT quantity, total_price
FROM order_details;

SELECT quantity, AVG(total_price) AS avg_total_price
FROM order_details
GROUP BY quantity
ORDER BY quantity;


-- What is the average quantity ordered per product?
SELECT p.prod_id, p.prod_name, AVG(od.quantity) AS avg_quantity
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY avg_quantity DESC;


-- How does the unit price vary across products and orders?
SELECT p.prod_id, p.prod_name, 
       MIN(od.each_price) AS min_unit_price,
       MAX(od.each_price) AS max_unit_price,
       AVG(od.each_price) AS avg_unit_price
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY avg_unit_price DESC;




